name: "Bug"
description: "不具合を報告する"
title: "[Bug] "
body:
  - type: "markdown"
    attributes:
      value: |
        不具合の内容を入力してください。
  - type: "textarea"
    id: "what-happened"
    attributes:
      label: "事象"
      description: "発生している問題を記載してください。"
    validations:
      required: true
  - type: "textarea"
    id: "steps"
    attributes:
      label: "再現手順"
      description: "再現手順を記載してください。"
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true
  - type: "textarea"
    id: "expected"
    attributes:
      label: "期待する動作"
      description: "本来の期待結果を記載してください。"
    validations:
      required: true
