name: "Feature"
description: "機能追加や改善を提案する"
title: "[Feature] "
body:
  - type: "markdown"
    attributes:
      value: |
        追加したい機能を入力してください。
  - type: "textarea"
    id: "overview"
    attributes:
      label: "概要"
      description: "何を実現したいかを記載してください。"
    validations:
      required: true
  - type: "textarea"
    id: "reason"
    attributes:
      label: "背景"
      description: "必要な理由や課題を記載してください。"
    validations:
      required: true
  - type: "textarea"
    id: "done-criteria"
    attributes:
      label: "完了条件"
      description: "完了とみなす条件を記載してください。"
    validations:
      required: true
