name: "Refactor"
description: "既存実装の改善を提案する"
title: "[Refactor] "
body:
  - type: "markdown"
    attributes:
      value: |
        改善対象と方針を入力してください。
  - type: "textarea"
    id: "target"
    attributes:
      label: "対象"
      description: "改善対象を記載してください。"
    validations:
      required: true
  - type: "textarea"
    id: "proposal"
    attributes:
      label: "改善方針"
      description: "どのように改善するかを記載してください。"
    validations:
      required: true
