name: "Task"
description: "対応タスクを起票する"
title: "[Task] "
body:
  - type: "markdown"
    attributes:
      value: |
        実施内容を入力してください。
  - type: "textarea"
    id: "summary"
    attributes:
      label: "内容"
      description: "タスク内容を記載してください。"
    validations:
      required: true
  - type: "textarea"
    id: "done-criteria"
    attributes:
      label: "完了条件"
      description: "完了とみなす条件を記載してください。"
    validations:
      required: true
